// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/v1/user.proto

package v1

import (
	fmt "fmt"
	entity "main/app/user-service/api/entity"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 创建用户
type CreateReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{0}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRes struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRes) Reset()         { *m = CreateRes{} }
func (m *CreateRes) String() string { return proto.CompactTextString(m) }
func (*CreateRes) ProtoMessage()    {}
func (*CreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{1}
}

func (m *CreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRes.Unmarshal(m, b)
}
func (m *CreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRes.Marshal(b, m, deterministic)
}
func (m *CreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRes.Merge(m, src)
}
func (m *CreateRes) XXX_Size() int {
	return xxx_messageInfo_CreateRes.Size(m)
}
func (m *CreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRes proto.InternalMessageInfo

func (m *CreateRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 查询用户详情
type GetOneReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneReq) Reset()         { *m = GetOneReq{} }
func (m *GetOneReq) String() string { return proto.CompactTextString(m) }
func (*GetOneReq) ProtoMessage()    {}
func (*GetOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{2}
}

func (m *GetOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneReq.Unmarshal(m, b)
}
func (m *GetOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneReq.Marshal(b, m, deterministic)
}
func (m *GetOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneReq.Merge(m, src)
}
func (m *GetOneReq) XXX_Size() int {
	return xxx_messageInfo_GetOneReq.Size(m)
}
func (m *GetOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneReq proto.InternalMessageInfo

func (m *GetOneReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOneRes struct {
	Data                 *entity.User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetOneRes) Reset()         { *m = GetOneRes{} }
func (m *GetOneRes) String() string { return proto.CompactTextString(m) }
func (*GetOneRes) ProtoMessage()    {}
func (*GetOneRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{3}
}

func (m *GetOneRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneRes.Unmarshal(m, b)
}
func (m *GetOneRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneRes.Marshal(b, m, deterministic)
}
func (m *GetOneRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneRes.Merge(m, src)
}
func (m *GetOneRes) XXX_Size() int {
	return xxx_messageInfo_GetOneRes.Size(m)
}
func (m *GetOneRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneRes proto.InternalMessageInfo

func (m *GetOneRes) GetData() *entity.User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 查询用户列表
type GetListReq struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListReq) Reset()         { *m = GetListReq{} }
func (m *GetListReq) String() string { return proto.CompactTextString(m) }
func (*GetListReq) ProtoMessage()    {}
func (*GetListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{4}
}

func (m *GetListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListReq.Unmarshal(m, b)
}
func (m *GetListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListReq.Marshal(b, m, deterministic)
}
func (m *GetListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListReq.Merge(m, src)
}
func (m *GetListReq) XXX_Size() int {
	return xxx_messageInfo_GetListReq.Size(m)
}
func (m *GetListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetListReq proto.InternalMessageInfo

func (m *GetListReq) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetListRes struct {
	List                 []*entity.User `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetListRes) Reset()         { *m = GetListRes{} }
func (m *GetListRes) String() string { return proto.CompactTextString(m) }
func (*GetListRes) ProtoMessage()    {}
func (*GetListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{5}
}

func (m *GetListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRes.Unmarshal(m, b)
}
func (m *GetListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRes.Marshal(b, m, deterministic)
}
func (m *GetListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRes.Merge(m, src)
}
func (m *GetListRes) XXX_Size() int {
	return xxx_messageInfo_GetListRes.Size(m)
}
func (m *GetListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRes proto.InternalMessageInfo

func (m *GetListRes) GetList() []*entity.User {
	if m != nil {
		return m.List
	}
	return nil
}

// 删除指定用户
type DeleteReq struct {
	// v: min:1#
	// v: Please select the user to be deleted.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" v:"min:1#Please select the user to be deleted."`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{6}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRes) Reset()         { *m = DeleteRes{} }
func (m *DeleteRes) String() string { return proto.CompactTextString(m) }
func (*DeleteRes) ProtoMessage()    {}
func (*DeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{7}
}

func (m *DeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRes.Unmarshal(m, b)
}
func (m *DeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRes.Marshal(b, m, deterministic)
}
func (m *DeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRes.Merge(m, src)
}
func (m *DeleteRes) XXX_Size() int {
	return xxx_messageInfo_DeleteRes.Size(m)
}
func (m *DeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateReq)(nil), "user.CreateReq")
	proto.RegisterType((*CreateRes)(nil), "user.CreateRes")
	proto.RegisterType((*GetOneReq)(nil), "user.GetOneReq")
	proto.RegisterType((*GetOneRes)(nil), "user.GetOneRes")
	proto.RegisterType((*GetListReq)(nil), "user.GetListReq")
	proto.RegisterType((*GetListRes)(nil), "user.GetListRes")
	proto.RegisterType((*DeleteReq)(nil), "user.DeleteReq")
	proto.RegisterType((*DeleteRes)(nil), "user.DeleteRes")
}

func init() {
	proto.RegisterFile("user/v1/user.proto", fileDescriptor_6eeaf71090dd90b5)
}

var fileDescriptor_6eeaf71090dd90b5 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x36, 0x54, 0x32, 0x15, 0xad, 0x7b, 0x2a, 0x11, 0x34, 0x2c, 0x88, 0x3d, 0xd8,
	0x2c, 0xd6, 0x7f, 0xa0, 0x42, 0x2f, 0x82, 0x10, 0xf0, 0xe2, 0x6d, 0x35, 0x73, 0x58, 0x48, 0xd3,
	0x98, 0x19, 0x0b, 0xfe, 0x3c, 0xff, 0x99, 0xec, 0x26, 0x4d, 0xc2, 0xda, 0x53, 0x87, 0xf7, 0xbd,
	0x7d, 0xbc, 0x99, 0x06, 0xc4, 0x37, 0x61, 0xad, 0xf6, 0xf7, 0xca, 0xfe, 0xa6, 0x55, 0xbd, 0xe3,
	0x9d, 0x08, 0xed, 0x1c, 0x5f, 0x60, 0xc9, 0x86, 0x7f, 0x06, 0x40, 0x5e, 0x43, 0xf4, 0x54, 0xa3,
	0x66, 0xcc, 0xf0, 0x4b, 0x08, 0x08, 0x4b, 0xbd, 0xc5, 0x45, 0x90, 0x04, 0xcb, 0x28, 0x73, 0xb3,
	0xbc, 0xec, 0x0d, 0x24, 0xce, 0x60, 0x6c, 0xf2, 0x16, 0x8f, 0x4d, 0x6e, 0xe1, 0x06, 0xf9, 0xb5,
	0x74, 0xaf, 0x7d, 0xb8, 0xea, 0x21, 0x89, 0x04, 0xc2, 0x5c, 0xb3, 0x76, 0x78, 0xb6, 0x3e, 0x4d,
	0x9b, 0x26, 0xe9, 0x1b, 0x61, 0x9d, 0x39, 0x22, 0xaf, 0x00, 0x36, 0xc8, 0x2f, 0x86, 0xd8, 0x86,
	0xcd, 0x61, 0x62, 0x72, 0x5a, 0x04, 0xc9, 0x64, 0x19, 0x65, 0x76, 0x94, 0xe9, 0x80, 0xbb, 0xbc,
	0xc2, 0x10, 0x3b, 0xc3, 0xbf, 0x3c, 0x4b, 0x6c, 0xb7, 0x67, 0x2c, 0x90, 0x8f, 0x76, 0x9b, 0xf5,
	0x90, 0xd6, 0xbf, 0x01, 0x84, 0xf6, 0xa1, 0xb8, 0x83, 0x69, 0xb3, 0xab, 0x38, 0x4f, 0xdd, 0x8d,
	0xba, 0xd3, 0xc4, 0x9e, 0x40, 0x72, 0x64, 0xdd, 0xcd, 0x7e, 0x07, 0x77, 0x77, 0x8a, 0xd8, 0x13,
	0xac, 0x5b, 0xc1, 0x49, 0x5b, 0x5f, 0xcc, 0x3b, 0xda, 0x6e, 0x1b, 0xfb, 0x4a, 0x1b, 0xdf, 0x54,
	0x3c, 0xc4, 0x77, 0xdb, 0xc4, 0x9e, 0x40, 0x72, 0xf4, 0x78, 0xfb, 0x7e, 0xc3, 0xb8, 0xad, 0x0a,
	0xcd, 0xa8, 0x74, 0x55, 0x29, 0xda, 0x7f, 0xae, 0x06, 0x82, 0x51, 0xed, 0x47, 0xf1, 0x31, 0x75,
	0xff, 0xfb, 0xc3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x1d, 0xcb, 0xb5, 0x26, 0x02, 0x00,
	0x00,
}
